version: '3.8'

services:
  app:
    image: nikitka22/myapp:2.0.0
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=mydatabase
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5433"