---
- name: Testing jre installation
  hosts: all
  vars:
    temurin_app: jre
#    temurin_certs:
#      - alias: my-private-ca
#        file: '{{ playbook_dir }}/my-private-ca.pem'
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Testing jre executable
      ansible.builtin.import_tasks: test-jre-exe.yml
- name: Testing jdk installation
  hosts: all
  vars:
    temurin_app: jdk
#    temurin_certs:
#      - alias: my-private-ca
#        file: '{{ playbook_dir }}/my-private-ca.pem'
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Testing jre executable
      ansible.builtin.import_tasks: test-jdk-exe.yml
